language: node_js

node_js:
  - 8

jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run coveralls
    - stage: publish
      script:
        - npm run semantic-release

stages:
  - test
  - name: publish
    if: branch = master
